### PR TITLE
Add function to search for scholar ID by name and affiliation

### PR DESCRIPTION
**Pull request by gjgetzinger**
Adds a basic function for searching for scholar ID by name and affiliation.

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
can you switch to using `curl` instead of `RCurl` according to [the tweet](https://twitter.com/opencpu/status/1131264122203492352).

**Comment by jefferis** [comment]
Thanks @GuangchuangYu. I fixed this up before merging. See commit 1927cda6891291ad8103a60edf6317e78f99a582

**Comment by jefferis** [comment]
NB I used the `get_resp` function which uses `httr::GET`, which ultimately uses the `curl` package.

**Comment by GuangchuangYu** [comment]
thanks @jefferis

**Pull request merged**
