### PR TITLE
updated fields-of-interest and availability metrics

### PR DESCRIPTION
**Pull request by TS404**
An extension of #94:
- update to handle the new layout for fields-of-interest (otherwise returns validation email in stead)
- update to handle the new separation of fields-of-interest (no longer comma separated)
- update to return the number of accessible and non-accessible publications
- update to define metrics in output

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
all checks have failed. pls check the error msg.

**Comment by TS404** [comment]
I think I've found all the issues. I was missing a closing bracket which caused the markdown errors, and there's a check in test-scholar.R that no longer works. I've also made it robust to whether or not a profile has availability stats or not.

**Comment by TS404** [comment]
@GuangchuangYu I thought I'd just ping you on this to confirm that the fixes I implemented now seem to be passing the checks.

**Comment by GuangchuangYu** [comment]
thanks.

**Comment by jefferis** [comment]
Thanks for this PR @TS404! Could I just check why 4020bac0fae1a1cd1458a91ccc267a4ae4c1d8b8 adds a `.RData` file? Normally these would not be included in a package ...

**Pull request merged**
