### PR TITLE
Adds get_coauthors and plot_coauthors

### PR DESCRIPTION
**Pull request by cimentadaj**
As discussed at https://github.com/jkeirstead/scholar/issues/53, here's the PR.

I implement two function: `get_coauthors` and `plot_coauthors`. Below is an example of how they work:

```r
library(scholar)
coauthor_network <- get_coauthors("amYIKXQAAAAJ&hl")
head(coauthor_network, 15)
#>                        author                  coauthors
#> 1  Herman G. van de Werfhorst                  Thijs Bol
#> 2  Herman G. van de Werfhorst            Daniele Checchi
#> 3  Herman G. van de Werfhorst         Frank van Tubergen
#> 4  Herman G. van de Werfhorst            wiemer salverda
#> 5  Herman G. van de Werfhorst          Gerbert Kraaykamp
#> 6                   Thijs Bol Herman G. van de Werfhorst
#> 7                   Thijs Bol              jaap dronkers
#> 8                   Thijs Bol              Kim A. Weeden
#> 9                   Thijs Bol          Andrea G. Forster
#> 10                  Thijs Bol                Bram Lancee
#> 11            Daniele Checchi        Massimiliano Bratti
#> 12            Daniele Checchi           Giorgio Brunello
#> 13            Daniele Checchi              Vito Peragine
#> 14            Daniele Checchi             Marco Leonardi
#> 15            Daniele Checchi           Giuseppe Bertola
plot_coauthors(coauthor_network, 3)
```
download

I created a set of 'helper' functions which actually do most of the work and I placed them in `zzz.R`. If you want me to move them elsewhere let me know. Some of these helper functions can be used in the already existing code of `scholar` and I think in fact it would be a good idea. I created a function called `compose_url` which wraps around some of your functions (`get_id`) into one function that creates a URL. Also, the workhorse behind `get_authors` is `list_authors` which you can also use inside `get_profile` and add a new slot in the list to return the names of the coauthors of that profile.  Also, whenever you use `GET`, I create the `get_resp` function which is a bit safer because it checks whether the response was successful or not and it retries 5 times otherwise raising an error. 

I could implement some of these changes in a separate PR, let me know if you're interested.

The function `plot_coauthors` is a bit heavy and adds 3 dependencies to create the graph. I'm sure there's a much lighter and easier way to do this. I'm not very proficient in network graphs but perhaps we can put a call out on Twitter to see if anyone is willing to simplify it and make it better/cleaner. 

If you think the PR is worth it,  let me know if I should add myself as a `ctb`. Also, the `get_resp` function was actually created and pushed by @ChuckFinley in `coauthornetwork`, so I'm not sure whethere he should be listed as a `ctb`.

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
thanks! Please add your  name and @ChuckFinley as `ctb`. 

Please go ahead to update the code as you propose.

**Comment by GuangchuangYu** [comment]
besides, you can add example of `plot_coauthors` in vignette.

**Comment by jefferis** [comment]
Can I just clarify which coauthors this returns. Is it only the ones that have a google scholar page?

**Comment by cimentadaj** [comment]
Yes, it is only those which are listed on the bottom-righ of a Google Scholar profile. Parsing article-specific coauthors is a bit trickier because names are usually slightly different between articles.

**Comment by jefferis** [comment]
> Yes, it is only those which are listed on the bottom-righ of a Google Scholar profile. Parsing article-specific coauthors is a bit trickier because names are usually slightly different between articles.

OK. But can I suggest that you update the documentation to make this point clearer? Thanks!

**Comment by cimentadaj** [comment]
How did you manage to install version 2.0.0? I installed with
devtools::install_github("tidyverse/tibble")  but it install version 1.4

-----------------------------------


Jorge Cimentada
*https://cimentadaj.github.io/ <https://cimentadaj.github.io/>*

**Comment by GuangchuangYu** [comment]
the github version is `1.4.99.9006`, which will be released to CRAN as v=2.0.0.

pls test with the github version of tibble.

**Comment by cimentadaj** [comment]
Using the latest version of both tibble and scholar, I don't get an error.

```r
library(devtools)
install_github("tidyverse/tibble")
#> Downloading GitHub repo tidyverse/tibble@master
#> from URL https://api.github.com/repos/tidyverse/tibble/tarball/master
#> Installing tibble
#> Running "C:/PROGRA~1/R/R-35~1.1/bin/x64/Rcmd.exe" INSTALL \
#>   "C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1" \
#>   "--library=C:/Users/jorge.cimentada/Documents/R/win-library/3.5" \
#>   --install-tests 
#> * installing *source* package 'tibble' ...
#> ** libs
#> 
#> *** arch - i386
#> c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O3 -Wall  -std=gnu99 -mtune=generic -c coerce.c -o coerce.o
#> c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
#> c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O3 -Wall  -std=gnu99 -mtune=generic -c matrixToDataFrame.c -o matrixToDataFrame.o
#> c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o tibble.dll tmp.def coerce.o init.o matrixToDataFrame.o -LC:/PROGRA~1/R/R-35~1.1/bin/i386 -lR
#> installing to C:/Users/jorge.cimentada/Documents/R/win-library/3.5/tibble/libs/i386
#> 
#> *** arch - x64
#> c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O2 -Wall  -std=gnu99 -mtune=generic -c coerce.c -o coerce.o
#> c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
#> c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O2 -Wall  -std=gnu99 -mtune=generic -c matrixToDataFrame.c -o matrixToDataFrame.o
#> c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o tibble.dll tmp.def coerce.o init.o matrixToDataFrame.o -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
#> installing to C:/Users/jorge.cimentada/Documents/R/win-library/3.5/tibble/libs/x64
#> ** R
#> ** tests
#> ** byte-compile and prepare package for lazy loading
#> ** help
#> *** installing help indices
#>   converting help for package     finding HTML links ...'tibble'
#>  done
#>     add_column                              html  
#>     add_row                                 html  
#>     as_tibble                               html  
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/as_tibble.Rd:82: file link 'matrix-class' in package 'methods' does not exist and so has been treated as a topic
#>     deprecated                              html  
#>     finding level-2 HTML links ... done
#> 
#>     enframe                                 html  
#>     formatting                              html  
#>     frame_matrix                            html  
#>     glimpse                                 html  
#>     is_tibble                               html  
#>     knit_print.trunc_mat                    html  
#>     lst                                     html  
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/lst.Rd:12: file link 'quos' in package 'rlang' does not exist and so has been treated as a topic
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/lst.Rd:27: file link 'list2' in package 'rlang' does not exist and so has been treated as a topic
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/lst.Rd:29: file link 'list2' in package 'rlang' does not exist and so has been treated as a topic
#>     name-repair-retired                     html  
#>     name-repair                             html  
#>     new_tibble                              html  
#>     reexports                               html  
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/reexports.Rd:17: file link 'obj_sum' in package 'pillar' does not exist and so has been treated as a topic
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/reexports.Rd:17: file link 'is_vector_s3' in package 'pillar' does not exist and so has been treated as a topic
#>     rownames                                html  
#>     subsetting                              html  
#>     tbl_df-class                            html  
#>     tbl_sum                                 html  
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/tbl_sum.Rd:15: file link 'obj_sum' in package 'pillar' does not exist and so has been treated as a topic
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/tbl_sum.Rd:18: file link 'is_vector_s3' in package 'pillar' does not exist and so has been treated as a topic
#>     tibble-package                          html  
#>     tibble                                  html  
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/tibble.Rd:13: file link 'quos' in package 'rlang' does not exist and so has been treated as a topic
#> Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc3cfa5c71/tidyverse-tibble-a248cf1/man/tibble.Rd:143: file link 'list2' in package 'rlang' does not exist and so has been treated as a topic
#>     tribble                                 html  
#>     view                                    html  
#> *** copying figures
#> ** building package indices
#> ** installing vignettes
#> ** testing if installed package can be loaded
#> *** arch - i386
#> *** arch - x64
#> * DONE (tibble)
#> In R CMD INSTALL
install_github("jkeirstead/scholar")
#> Downloading GitHub repo jkeirstead/scholar@master
#> from URL https://api.github.com/repos/jkeirstead/scholar/tarball/master
#> Installing scholar
#> Running "C:/PROGRA~1/R/R-35~1.1/bin/x64/Rcmd.exe" INSTALL \
#>   "C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpmINFl7/devtools77fc4899fc2/jkeirstead-scholar-18b30b3" \
#>   "--library=C:/Users/jorge.cimentada/Documents/R/win-library/3.5" \
#>   --install-tests 
#> * installing *source* package 'scholar' ...
#> ** R
#> ** inst
#> ** byte-compile and prepare package for lazy loading
#> ** help
#> *** installing help indices
#>   converting help for package     finding HTML links ...'scholar'
#>  done
#>     compare_scholar_careers                 html  
#>     compare_scholars                        html  
#>     get_article_cite_history                html  
#>     get_citation_history                    html  
#>     get_coauthors                           html  
#>     get_complete_authors                    html  
#>     get_impactfactor                        html  
#>     get_journalrank                         html  
#>     get_num_articles                        html  
#>     get_num_distinct_journals               html  
#>     get_num_top_journals                    html  
#>     get_oldest_article                      html  
#>     get_profile                             html  
#>     get_publications                        html  
#>     plot_coauthors                          html  
#>     predict_h_index                         html  
#>     scholar                                 html  
#>     tidy_id                                 html  
#> ** building package indices
#> ** installing vignettes
#> ** testing if installed package can be loaded
#> *** arch - i386
#> *** arch - x64
#> * DONE (scholar)
#> In R CMD INSTALL
library(scholar)

coauthor_network <- get_coauthors('amYIKXQAAAAJ&hl', n_coauthors = 5)
coauthor_network
#>                        author                  coauthors
#> 1  Herman G. Van De Werfhorst                  Thijs Bol
#> 2  Herman G. Van De Werfhorst            Daniele Checchi
#> 3  Herman G. Van De Werfhorst         Frank Van Tubergen
#> 4  Herman G. Van De Werfhorst            Wiemer Salverda
#> 5  Herman G. Van De Werfhorst Jonathan Jan Benjamin Mijs
#> 6                   Thijs Bol Herman G. Van De Werfhorst
#> 7                   Thijs Bol              Jaap Dronkers
#> 8                   Thijs Bol          Andrea G. Forster
#> 9                   Thijs Bol              Kim A. Weeden
#> 10                  Thijs Bol                Bram Lancee
#> 11            Daniele Checchi        Massimiliano Bratti
#> 12            Daniele Checchi           Giorgio Brunello
#> 13            Daniele Checchi              Vito Peragine
#> 14            Daniele Checchi             Marco Leonardi
#> 15            Daniele Checchi           Giuseppe Bertola
#> 16         Frank Van Tubergen                 Ineke Maas
#> 17         Frank Van Tubergen           Matthijs Kalmijn
#> 18         Frank Van Tubergen            Agnieszka Kanas
#> 19         Frank Van Tubergen Herman G. Van De Werfhorst
#> 20         Frank Van Tubergen            Marcel Coenders
#> 21            Wiemer Salverda                   Ive Marx
#> 22            Wiemer Salverda Herman G. Van De Werfhorst
#> 23            Wiemer Salverda              Stephen Bazen
#> 24            Wiemer Salverda            Daniele Checchi
#> 25            Wiemer Salverda           Anthony Atkinson
#> 26 Jonathan Jan Benjamin Mijs Herman G. Van De Werfhorst
#> 27 Jonathan Jan Benjamin Mijs               Maurice Crul
#> 28 Jonathan Jan Benjamin Mijs            Philipp Schnell
#> 29 Jonathan Jan Benjamin Mijs               Bowen Paulle
#> 30 Jonathan Jan Benjamin Mijs             Michele Lamont

plot_coauthors(coauthor_network, 2)
```
image

Created on 2018-11-29 by the reprex package (v0.2.0).

**Comment by GuangchuangYu** [comment]
did you load `tibble` before you installing github version? if yes, please test the code with fresh R session.

    Quitting from lines 131-132 (scholar.Rmd)
    Error: processing vignette 'scholar.Rmd' failed with diagnostics:
    Evaluation error: Columns 1, 2 must be named.
    Use .name_repair to specify repair..
    Execution halted

According to the error, there should be `as_data_frame` or `as_tibble` to an unamed data.frame or matrix.

**Comment by cimentadaj** [comment]
I still cannot reproduce this. 

```r
>   library(devtools)
>   install_github("tidyverse/tibble", force = TRUE)
Downloading GitHub repo tidyverse/tibble@master
√  checking for file 'C:\Users\jorge.cimentada\AppData\Local\Temp\Rtmp8U5DKo\remotesd61c78bf7853\tidyverse-tibble-ddc9110/DESCRIPTION' ... 
-  preparing 'tibble': (343ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'tibble_1.4.99.9006.tar.gz'
   
Installing package into ‘C:/Users/jorge.cimentada/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'tibble' ...
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O3 -Wall  -std=gnu99 -mtune=generic -c coerce.c -o coerce.o
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O3 -Wall  -std=gnu99 -mtune=generic -c matrixToDataFrame.c -o matrixToDataFrame.o
C:/RBuildTools/3.5/mingw_32/bin/gcc -shared -s -static-libgcc -o tibble.dll tmp.def coerce.o init.o matrixToDataFrame.o -LC:/PROGRA~1/R/R-35~1.1/bin/i386 -lR
installing to C:/Users/jorge.cimentada/R/win-library/3.5/tibble/libs/i386

*** arch - x64
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O2 -Wall  -std=gnu99 -mtune=generic -c coerce.c -o coerce.o
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -std=gnu99         -O2 -Wall  -std=gnu99 -mtune=generic -c matrixToDataFrame.c -o matrixToDataFrame.o
C:/RBuildTools/3.5/mingw_64/bin/gcc -shared -s -static-libgcc -o tibble.dll tmp.def coerce.o init.o matrixToDataFrame.o -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
installing to C:/Users/jorge.cimentada/R/win-library/3.5/tibble/libs/x64
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'tibble'
    finding HTML links ... done
    add_column                              html  
    add_row                                 html  
    as_tibble                               html  
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/as_tibble.Rd:82: file link 'matrix-class' in package 'methods' does not exist and so has been treated as a topic
    deprecated                              html  
    finding level-2 HTML links ... done

    enframe                                 html  
    formatting                              html  
    frame_matrix                            html  
    glimpse                                 html  
    is_tibble                               html  
    knit_print.trunc_mat                    html  
    lst                                     html  
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/lst.Rd:12: file link 'quos' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/lst.Rd:27: file link 'list2' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/lst.Rd:29: file link 'list2' in package 'rlang' does not exist and so has been treated as a topic
    name-repair-retired                     html  
    name-repair                             html  
    new_tibble                              html  
    reexports                               html  
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/reexports.Rd:17: file link 'obj_sum' in package 'pillar' does not exist and so has been treated as a topic
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/reexports.Rd:17: file link 'is_vector_s3' in package 'pillar' does not exist and so has been treated as a topic
    rownames                                html  
    subsetting                              html  
    tbl_df-class                            html  
    tbl_sum                                 html  
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/tbl_sum.Rd:15: file link 'obj_sum' in package 'pillar' does not exist and so has been treated as a topic
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/tbl_sum.Rd:18: file link 'is_vector_s3' in package 'pillar' does not exist and so has been treated as a topic
    tibble-package                          html  
    tibble                                  html  
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/tibble.Rd:13: file link 'quos' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/jorge.cimentada/AppData/Local/Temp/RtmpgfSJOr/R.INSTALLc0f43d4b7afd/tibble/man/tibble.Rd:143: file link 'list2' in package 'rlang' does not exist and so has been treated as a topic
    tribble                                 html  
    view                                    html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (tibble)
In R CMD INSTALL
>   install_github("jkeirstead/scholar", force = TRUE)
Downloading GitHub repo jkeirstead/scholar@master
√  checking for file 'C:\Users\jorge.cimentada\AppData\Local\Temp\Rtmp8U5DKo\remotesd61c7b254391\jkeirstead-scholar-18b30b3/DESCRIPTION' ... 
-  preparing 'scholar':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'scholar_0.1.7.tar.gz'
   
Installing package into ‘C:/Users/jorge.cimentada/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'scholar' ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'scholar'
    finding HTML links ... done
    compare_scholar_careers                 html  
    compare_scholars                        html  
    get_article_cite_history                html  
    get_citation_history                    html  
    get_coauthors                           html  
    get_complete_authors                    html  
    get_impactfactor                        html  
    get_journalrank                         html  
    get_num_articles                        html  
    get_num_distinct_journals               html  
    get_num_top_journals                    html  
    get_oldest_article                      html  
    get_profile                             html  
    get_publications                        html  
    plot_coauthors                          html  
    predict_h_index                         html  
    scholar                                 html  
    tidy_id                                 html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (scholar)
In R CMD INSTALL

>   library(tibble)
>   library(scholar)
>   coauthor_network <- get_coauthors('amYIKXQAAAAJ&hl', n_coauthors = 5)
>   coauthor_network
                       author                  coauthors
1  Herman G. Van De Werfhorst                  Thijs Bol
2  Herman G. Van De Werfhorst            Daniele Checchi
3  Herman G. Van De Werfhorst         Frank Van Tubergen
4  Herman G. Van De Werfhorst            Wiemer Salverda
5  Herman G. Van De Werfhorst Jonathan Jan Benjamin Mijs
6                   Thijs Bol Herman G. Van De Werfhorst
7                   Thijs Bol              Jaap Dronkers
8                   Thijs Bol          Andrea G. Forster
9                   Thijs Bol              Kim A. Weeden
10                  Thijs Bol                Bram Lancee
11            Daniele Checchi        Massimiliano Bratti
12            Daniele Checchi           Giorgio Brunello
13            Daniele Checchi              Vito Peragine
14            Daniele Checchi             Marco Leonardi
15            Daniele Checchi           Giuseppe Bertola
16         Frank Van Tubergen                 Ineke Maas
17         Frank Van Tubergen           Matthijs Kalmijn
18         Frank Van Tubergen            Agnieszka Kanas
19         Frank Van Tubergen Herman G. Van De Werfhorst
20         Frank Van Tubergen            Marcel Coenders
21            Wiemer Salverda                   Ive Marx
22            Wiemer Salverda Herman G. Van De Werfhorst
23            Wiemer Salverda              Stephen Bazen
24            Wiemer Salverda            Daniele Checchi
25            Wiemer Salverda           Anthony Atkinson
26 Jonathan Jan Benjamin Mijs Herman G. Van De Werfhorst
27 Jonathan Jan Benjamin Mijs               Maurice Crul
28 Jonathan Jan Benjamin Mijs            Philipp Schnell
29 Jonathan Jan Benjamin Mijs               Bowen Paulle
30 Jonathan Jan Benjamin Mijs             Michele Lamont
>   plot_coauthors(coauthor_network, 2)
```
network_plot

**Comment by cimentadaj** [comment]
Hi @GuangchuangYu , moreover, I just updated the repository to your latest changes in my fork and ran `devtools::check()` which runs the vignette and this is the output (no error on `tibble`)

```r
devtools::check()
Updating scholar documentation
Warning: roxygen2 requires Encoding: UTF-8
Writing NAMESPACE
Loading scholar
Writing NAMESPACE
-- Building --------------------------------------------------------- scholar --
Setting env vars:
* CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
* CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
* CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
--------------------------------------------------------------------------------
√  checking for file 'C:\Users\Cimentadaj\Downloads\repositories\scholar/DESCRIPTION' ... 
-  preparing 'scholar': (800ms)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
√  creating vignettes (25.3s)
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'scholar_0.1.7.tar.gz'
   
-- Checking --------------------------------------------------------- scholar --
Setting env vars:
* _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
* _R_CHECK_CRAN_INCOMING_REMOTE_    : FALSE
* _R_CHECK_CRAN_INCOMING_           : FALSE
* _R_CHECK_FORCE_SUGGESTS_          : FALSE
-- R CMD check ---------------------------------------------------------------------------------
-  using log directory 'C:/Users/Cimentadaj/AppData/Local/Temp/RtmpI5qVHj/scholar.Rcheck' (796ms)
-  using R version 3.5.1 (2018-07-02)
-  using platform: x86_64-w64-mingw32 (64-bit)
-  using session charset: ISO8859-1
-  using options '--no-manual --as-cran'
√  checking for file 'scholar/DESCRIPTION'
-  this is package 'scholar' version '0.1.7'
√  checking package namespace information
√  checking package dependencies (744ms)
√  checking if this is a source package ...
√  checking if there is a namespace
√  checking for executable files (643ms)
√  checking for hidden files and directories ... 
√  checking for portable file names ... 
√  checking serialization versions ... 
√  checking whether package 'scholar' can be installed (6.7s)
√  checking installed package size ... 
√  checking package directory (373ms)
√  checking 'build' directory ...
√  checking DESCRIPTION meta-information (497ms)
√  checking top-level files ...
√  checking for left-over files
√  checking index information ... 
√  checking package subdirectories (453ms)
√  checking R files for non-ASCII characters ... 
√  checking R files for syntax errors ... 
√  checking whether the package can be loaded (723ms)
√  checking whether the package can be loaded with stated dependencies (662ms)
√  checking whether the package can be unloaded cleanly (768ms)
√  checking whether the namespace can be loaded with stated dependencies (666ms)
√  checking whether the namespace can be unloaded cleanly (788ms)
√  checking loading without being on the library search path (849ms)
√  checking dependencies in R code (1.3s)
√  checking S3 generic/method consistency (970ms)
√  checking replacement functions (549ms)
√  checking foreign function calls (860ms)
N  checking R code for possible problems (5.1s)
   author_position: no visible binding for global variable 'tail'
   Undefined global functions or variables:
     tail
   Consider adding
     importFrom("utils", "tail")
   to your NAMESPACE file.
√  checking Rd files ... 
√  checking Rd metadata ... 
√  checking Rd line widths ... 
√  checking Rd cross-references ... 
√  checking for missing documentation entries (645ms)
√  checking for code/documentation mismatches (2.2s)
√  checking Rd \usage sections (1.2s)
√  checking Rd contents ... 
√  checking for unstated dependencies in examples ... 
√  checking R/sysdata.rda ... 
√  checking installed files from 'inst/doc' ... 
√  checking files in 'vignettes' ... 
√  checking examples (14.7s)
   ** found \donttest examples: check also with --run-donttest
√  checking for unstated dependencies in vignettes ... 
√  checking package vignettes in 'inst/doc' ... 
√  checking re-building of vignette outputs (18.2s)
   
   See
     'C:/Users/Cimentadaj/AppData/Local/Temp/RtmpI5qVHj/scholar.Rcheck/00check.log'
   for details.
   
   
-- R CMD check results ------------------------------------------------------ scholar 0.1.7 ----
Duration: 1m 3.5s

> checking R code for possible problems ... NOTE
  author_position: no visible binding for global variable 'tail'
  Undefined global functions or variables:
    tail
  Consider adding
    importFrom("utils", "tail")
  to your NAMESPACE file.

0 errors √ | 0 warnings √ | 1 note x
```

Just to check, here's the `tibble` version

```r
packageVersion("tibble")
[1] ‘1.4.99.9006’
```

which is the latest version from `tibble`: [https://github.com/tidyverse/tibble/blob/master/DESCRIPTION](https://github.com/tidyverse/tibble/blob/master/DESCRIPTION)

**Pull request merged**
